### ISSUE TITLE
No module named 'nmap'

### ISSUE THREAD

**Issue by Amplxfy** [k4m4/kickthemout#250]
## Checklist for submitting an issue to `KickThemOut`:

- [x] I have carefully read the [README](https://github.com/k4m4/kickthemout/blob/master/README.rst) file and haven't managed to resolve my issue.
- [x] I have searched the [issues](https://github.com/k4m4/kickthemout/issues?utf8=%E2%9C%93&q=is%3Aissue) of this repo and believe that this is not a duplicate.
- [x] I am running the latest version of KickThemOut.

 

- **OS name & version**: 
- **Python version**: 
- **Scapy version**: 
- **Nmap version**: 
- **Link of [Gist](https://gist.github.com/)**: 

<br/ >

- **Description**:

**Comment by Amplxfy** [comment]
Theres an error message telling me that there "no module named nmap". I have read the read me and followed the instructions given, but it still wont work.

**Comment by xdavidhu** [comment]
Hi!

Make sure to install nmap:
`sudo apt-get update && sudo apt-get install nmap`

And all the Python modules:
`sudo -H pip3 install -r requirements.txt`

This should fix the issue you are experiencing.

**Comment by SheesAli** [comment]
sudo apt-get update && sudo apt-get install nmap
I have done above step still showing same error

**Comment by k4m4** [comment]
@Amplxfy any progress with this?

**Comment by Amplxfy** [comment]
Unfortunately not. It’s also saying “command not found” when I enter “sudo
-H pip3 install -r requirements.txt”. I’m not sure if that has anything to
do with it.

**Comment by k4m4** [comment]
@Amplxfy the command you are running doesn't seem to be correct. Please refer to the readme file for full installation instructions. Thanks.

**Comment by 0rigin5** [comment]
hello. i am having the same issure on kali linux. i do have nmap installed and have run all commands noted in the readme.md file. any ideas on wat could be the issue?

thanks

**Comment by Devloger** [comment]
Same issue here.

**Comment by Devloger** [comment]
I don't think you guys do this right, cuz it works.

instead of running by
sudo python...
do
sudo python3...

should work

**Comment by k4m4** [comment]
It seems that this issue has been solved. If anyone is still experiencing the same error, please try going through the installation again - carefully. Thanks!

**Comment by sontqq** [comment]
I experience the same error.
Linux raspberrypi 4.14.52-v7+ #1123 SMP Wed Jun 27 17:35:49 BST 2018 armv7l GNU/Linux

**Comment by Pharanger** [comment]
If you're running some version of Debian like Kali linux, try this:
`sudo apt-get install python3`
`sudo apt-get install python3-pip`
`sudo -H pip3 install -r requirements.txt`
I was having the same problem then I tried this
